version: "3.9"  # Updated version

services:
  zabbix-server:
    image: zabbix/zabbix-server-centos:6.8-latest
    restart: unless-stopped
    environment:
      ZABBIX_DB_HOST: postgres
      ZABBIX_DB_NAME: zabbix
      ZABBIX_DB_USER: zabbix
      ZABBIX_DB_PASSWORD: password  # Replace with the same password
      ZABBIX_SERVER_HOSTNAME: zabbix-server
    volumes:
      - ./zabbix:/etc/zabbix
      - ./zabbix/logs:/var/log/zabbix
    depends_on:
      - postgres
  zabbix-agent:
    image: zabbix/zabbix-agent2:6.8-latest
    restart: unless-stopped
    environment:
      ZABBIX_SERVER_HOST: zabbix-server
      ZABBIX_SERVER_PORT: 10051
    volumes:
      - ./zabbix/agent/conf:/etc/zabbix/agent2
